# General settings:
folder_to_watch: /.../test-WSIs # the folder to watch for new wsi files. New imported files will be processed and moved to the target folder, or renamed.
target_folder: '' # the folder where the processed files will be moved to (NOT IMPLEMENTED YET!)
wsi_types: ['.ndpi']
debug_mode: true # if true, more informations will be printed and or logged into the log file (e.g. debug images are stored in folder_to_watch/metadata_debug).
# how to store the extracted metadata
rename_wsi_files: true # if true, the wsi files will be renamed (extracted from the metadata)
force_meta_extraction: false # if true, the metadata will be extracted even if the metadata for a wsi file is already extracted (e.g. according to the renaming pattern)
wsi_macro_img_tag: 'macro' # this tag is used to identify the macro images in the wsi files
slide_label_classifier: # pretrained label-classifier settings:
  model_path: 'tools_labelTypeClassification/resnet_results/4/trained_model.pth' # the path to the pretrained label classifier model
  model_type: 'resnet18' # the type of the model, e.g. 'resnet18', 'resnet50', ...

label_configs:
  CMCP:
    # ROI-Set and macro-img-preprocessing settings:
    ROI_set_file: 'config/RoiSetCMCP.zip' # the file with the ROIs for the OCR (and datamatrix) extraction
    wsi_macro_img_rotation: 90 # how to rotate the image in degrees, clockwise. Allowed values: [0, 90, 180, 270, -90, -180, None]
    ROI_set_ref_res: [1155, 395] # the x-y resolution of the macro-image which has been used to create the RoiSet.zip file
    renaming_pattern: '{slide-id}_{staining}' # the pattern for the renaming of the wsi files. Needs to have a shape like '{slide-id}_{staining}'

    # rules for the metadata extraction:
    extraction_rules: # the rules for the metadata extraction
      slide-id: # rules and settings of the 'slide-id' field
        allowed_chars: '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZv-' # in our case, other characters do not appear in any slide-id.
        is_datamatrix: false
        plausibility_regex_check:
        - '^(CMCP.{0,2}v)' # slide-id has to start with 'CMCP', then 0-2 characters, then 'v'
        - '(-)' # slide-id should not contain a '-'
        replacement_patterns: # replacement patterns
        - ['\s+$', ''] # remove spaces at the end
        - ['^.*?CMCP', 'CMCP'] # remove everything before 'CMCP', e.g. '-CMCP1234' -> 'CMCP1234'
      staining:
        allowed_chars: 'HEPAS'
        is_datamatrix: false
        plausibility_regex_check:
        - '(HE)' # should contain 'HE' (in this case there are only HE stained slides....
        replacement_patterns:
        - ['\s+$', ''] # remove spaces at the end
  IHC:
    # ROI-Set and macro-img-preprocessing settings:
    ROI_set_file: 'config/RoiSetIHC.zip' # the file with the ROIs for the OCR (and datamatrix) extraction
    wsi_macro_img_rotation: 90 # how to rotate the image in degrees, clockwise. Allowed values: [0, 90, 180, 270, -90, -180, None]
    ROI_set_ref_res: [1155, 395] # the x-y resolution of the macro-image which has been used to create the RoiSet.zip file
    renaming_pattern: '{slide-id}' # the pattern for the renaming of the wsi files. Needs to have a shape like '{slide-id}_{staining}'

    # rules for the metadata extraction:
    extraction_rules: # the rules for the metadata extraction
      slide-id: # rules and settings of the 'slide-id' field
        allowed_chars: null
        is_datamatrix: true
        plausibility_regex_check: null'
        replacement_patterns: null