import os.path
import datetime
from tools_MetadataExtraction.HitchhikersGuide import HitchhickerGuide

id_seperation_symbol = ""
valid_case_id_prefixes = ["E", "R", "F", 'S', 'T']

def is_valid_slide_id(slide_id: str) -> bool:
    if len(slide_id) > 11:
        if slide_id[11] == "S" and slide_id[0] in valid_case_id_prefixes:
            if slide_id[1:11].isdigit():
                return True
    return False

def is_valid_case_id(case_id: str) -> bool:
    if len(case_id) > 11:
        if case_id[0] in valid_case_id_prefixes:
            if case_id[1:11].isdigit():
                case_year = int(case_id[1:5])
                if case_year <= int(datetime.datetime.now().year):  # the year should not be in the future
                    return True
    return False

def get_slide_meta_data(path_to_slide, slide_reader: HitchhickerGuide, case_id_length=6):
    '''
    returns a dict which contains all the meta info about the slide using qr-codes and OCR
    Returned dict needs the following schema (because our patho-PACS works with this schema):

    {
        "RequestId": "E001",
        "ExamId": "E001",
        "Staining": {
            "Name": "HE"
        },
        "Block": {
            "Name": "A"
        },
        "SpecimenBox": {
            "Name": "1"
        }
    }

    Alternatively, the metadata file can be used to specify a SlideId. In that case, any other properties will be ignored.
    { "SlideId": "LP123-B38-13" }

    The metadata file must be named the same as the image file, put with an .import extension. So if the image file is called slide123.ndpi, the meta data is put in a file called slide123.ndpi.import. It should be placed in the same directory as the image file.

    The following information is mandatory (if not using SLIDE ID)
        - Accession number (also known as lab number or request number) (seems to be usually equals to the Exam/Case ID)
        - Specimen and/or Block (e.g. 1A, 1B, 2A etc.)
        - Stain (e.g. H&E, Ki67, HER2 etc.)
    The Accession number / Lab Number / Request Number is mandatory, the Exam ID is not.
    RequestID is the Number generated by the LIS that identifies the order for the Study,

    Behavior of this function:
    - If OCR or data-matrix reader fails, the file-name will be used as slide-id in order to create any meta-data.
    - if the slide-id passes the is_know_slide_id check, no OCR-based metadata extraction is necessary and only the slide-id will be saved in the meta_data file
    - If not, the slide-id is not saved in the output meta-data-file, but all the other meta-infos like CaseID and RequestID, localisation and stain.

    '''

    meta_data = {}

    try:
        text_datamatrix = slide_reader.text_datamatrix
        slide_id = text_datamatrix[0].data.decode('UTF-8')
        #print(f"slide id (qr code decoded): {slide_id}")
    except Exception as e:
        slide_id = os.path.basename(path_to_slide)
        if "." in slide_id:
            slide_id = slide_id.split(".")[0]
        print(f"WARNING: Failed to decode data-matrix of {path_to_slide} ({e}). Using file-name as slide_id ({slide_id}).")

    # if valid slide id is found, meta-data consists of slide-id and Staining.
    if is_valid_slide_id(slide_id):
        meta_data["SlideId"] = slide_id # Our Slides PACS will use this id to identify the slide
        meta_data["Staining"] = {"Name": slide_reader.stain}

    else: # it is a roche- or other  slide, so we have to check for the detected texts on the slide to get meta-data

        print(f"WARNING: Slide-ID {slide_id} is not valid. Using OCR to extract meta-data.")

        # collect meta-data via ocr:
        case_id = slide_reader.case

        # ensure that cas_id has always length 6:
        if len(case_id) < case_id_length:
            case_id = "0"*(case_id_length-len(case_id)) + case_id

        meta_data["ExamId"] = (slide_reader.LabelText.number_circle + id_seperation_symbol +
                               "20" + slide_reader.LabelText.year + id_seperation_symbol + case_id + "S")

        meta_data["RequestId"] = meta_data["ExamId"]

        meta_data["Staining"] = {"Name": slide_reader.stain}

        meta_data["Block"] = {"Name": slide_reader.block.replace(' ', '')}
        #meta_data["SpecimenBox"] = {"Name": ocr_results.fraction}

    return meta_data


if __name__ == "__main__":

    test_slides = ["./test_data/test#2.ndpi", "./test_data/test#3.ndpi"]

    for test_file in test_slides:
        meta_data = get_slide_meta_data(test_file, HitchhickerGuide(test_file))
        print(f"meta-data of {test_file}:\n{meta_data}\n")
